OPENWEATHER_APPID = "5a9bfad01ab419063b1d3f3463f73446"
MONGODB_DBNAME = "WeatherDEDBCluster"
MONGODB_SERVER_URI = "mongodb+srv://openweatherdatalake:zmf2qaQ6v5y34guw@weatherdedbcluster.mpqgtcu.mongodb.net/?retryWrites=true&w=majority&appName=WeatherDEDBCluster"
